homepageURL = "http://192.168.11.103:8080/web/cloudclinik/cc-login"
loginID = "_58_login"
passwordID = "_58_password"
loginButtonXpath = "//button[@type = 'submit']"
RegbuttXpath = "//a[@href = 'http://192.168.11.103:8080/web/cloudclinik/register-patient']"
fNameID = "_SignUp_WAR_CloudClinikportlet_:form:Name"
lNameID = "_SignUp_WAR_CloudClinikportlet_:form:LastName"
mNoID = "_SignUp_WAR_CloudClinikportlet_:form:Mobile"
cnicID = "_SignUp_WAR_CloudClinikportlet_:form:CNIC"
stateID = "_SignUp_WAR_CloudClinikportlet_:form:State"
stateNameID = "//li[@data-label = 'Punjab']"
cityID = "_SignUp_WAR_CloudClinikportlet_:form:City"
cityNameID = "//li[@data-label = 'Lahore']"
cPersonID = "_SignUp_WAR_CloudClinikportlet_:form:emergencyContactPerson"
cPersonMobID = "_SignUp_WAR_CloudClinikportlet_:form:emergencyContactNumber"
cPersonRelID = "_SignUp_WAR_CloudClinikportlet_:form:emergencyContactRelation_label"
cPersonRelNameXpath = "//li[@data-label = 'Friend']"
empStatusID = "_SignUp_WAR_CloudClinikportlet_:form:employeeStatu_label"
empStatusNameXpath = "//li[@data-label = 'Executive Staff']"
empDeptID = "_SignUp_WAR_CloudClinikportlet_:form:employeeDeparmentLabel_label"
empDeptNameXpath = "//li[@data-label = 'Software Quality Assurance']"
proceedID = "_SignUp_WAR_CloudClinikportlet_:form:AssitantSignUpBtn"
regCmpID = "_SignUp_WAR_CloudClinikportlet_:assistantConfirmation:confirmationalert_title"

anncFormID = "_userInfo_WAR_CloudClinikportlet_:startAnouncementForm:j_idt68"
confgXpath = '//*[@id="myId"]/li[17]/a/span'
HFprefXpath = "//a[@href = 'http://192.168.11.103:8080/web/cloudclinik/health-facility-preferences']"
pCNICID = "_HealthFacilityPreferences_WAR_CloudClinikportlet_:maintabview:HF_form:qidRequiredCheck"
pLastNameID = "_HealthFacilityPreferences_WAR_CloudClinikportlet_:maintabview:HF_form:RequiredCheck"
pEmcID = "_HealthFacilityPreferences_WAR_CloudClinikportlet_:maintabview:HF_form:emergencyContactNumberRequiredCheck"
pDeptID = "_HealthFacilityPreferences_WAR_CloudClinikportlet_:maintabview:HF_form:statusDepartmentRequiredCheck"
pSaveID = "_HealthFacilityPreferences_WAR_CloudClinikportlet_:maintabview:HF_form:j_idt131"

